# Generated by Django 4.2.9 on 2024-02-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
