# Generated by Django 4.2.9 on 2024-02-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0003_profile_notifications_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profpics'),
        ),
    ]
