# Generated by Django 4.2.9 on 2024-03-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0005_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='activeParticipants',
            field=models.ManyToManyField(blank=True, related_name='active_participant_chats', to='socialMedia.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chatNotifications',
            field=models.IntegerField(default=0),
        ),
    ]
