# Generated by Django 4.2.9 on 2024-03-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialMedia', '0006_chat_activeparticipants_profile_chatnotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chatNotifications',
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialMedia.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='chatNotifications',
            field=models.ManyToManyField(blank=True, to='socialMedia.chatnotification'),
        ),
    ]
