# Generated by Django 4.2.9 on 2024-03-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0007_remove_profile_chatnotifications_chatnotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chatNotifications',
        ),
    ]
