# Generated by Django 4.2.9 on 2024-03-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0008_remove_profile_chatnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messages',
            field=models.IntegerField(default=0),
        ),
    ]
